[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = []

[mgr]
border_symbol = " "


[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[select]
hovered = { bg = "blue" }

[indicator]
padding  = { open = "█", close = "█" }
